Remove debug.cpp to avoid multiple definition error
Linker error: "multiple definition of ..." occurs in some repositories
as functions:
 -debug, debugf, debug_put, debug_hex, debug_int
 -printf_array, printf_ipv6_address and printf_string
are found from debug.cpp and from also from nanomesh libService.

Tracing functions should be used from libservice file ns_trace.c/h
and therefore tracing function can be removed from debug.cpp.